import type { Screenshot } from "@/components/ui/screenshot-gallery";

export const screenshots: Screenshot[] = [
  {
    id: "dashboard-overview",
    title: "Dashboard Overview",
    category: "Dashboard",
    image: "/screenshots/dashboard/overview.png",
    description: "Main dashboard with application stats, outreach chart, pipeline donut, and recent activity.",
    technicalNotes: ["Recharts", "Server Component", "Aggregated queries"],
  },
  {
    id: "companies-list",
    title: "Company List",
    category: "Companies",
    image: "/screenshots/companies/list.png",
    description: "Location-scoped company management with CSV import, search, and bulk operations.",
    technicalNotes: ["DataTable", "GIN trigram search", "CSV parser"],
  },
  {
    id: "company-detail",
    title: "Company Detail",
    category: "Companies",
    image: "/screenshots/companies/detail.png",
    description: "Detailed company view with all fields from the CSV format, editing, and application history.",
    technicalNotes: ["FormCard pattern", "Snapshot on send"],
  },
  {
    id: "applications-pipeline",
    title: "Application Pipeline",
    category: "Applications",
    image: "/screenshots/applications/pipeline.png",
    description: "Application tracking with status pipeline from Sent through to Hired, with Gmail thread sync.",
    technicalNotes: ["Gmail threadId", "Status pipeline", "Reply sync"],
  },
  {
    id: "application-thread",
    title: "Application Thread",
    category: "Applications",
    image: "/screenshots/applications/thread.png",
    description: "Full email conversation thread for an application, showing outgoing and incoming messages.",
    technicalNotes: ["EmailMessage model", "Gmail API sync"],
  },
  {
    id: "outreach-send",
    title: "Send Application",
    category: "Outreach",
    image: "/screenshots/outreach/send.png",
    description: "Email composition with template selection, resume attachment, and Gmail API sending.",
    technicalNotes: ["Gmail API", "Template placeholders", "Personalised rendering"],
  },
  {
    id: "templates-editor",
    title: "Email Template Editor",
    category: "Outreach",
    image: "/screenshots/outreach/templates.png",
    description: "Template management with placeholder support for companyName, hiringRoles, senderName.",
    technicalNotes: ["Mustache-style placeholders", "Default template"],
  },
  {
    id: "resumes-list",
    title: "Resume Manager",
    category: "Resumes",
    image: "/screenshots/resumes/list.png",
    description: "Multiple resume management with default selection, private Cloudinary storage, and share links.",
    technicalNotes: ["Cloudinary authenticated", "Signed URLs", "Share tokens"],
  },
  {
    id: "subscription-portal",
    title: "Subscription Portal",
    category: "Subscription",
    image: "/screenshots/subscription/portal.png",
    description: "User-facing subscription management with plan details, payment history, and timeline.",
    technicalNotes: ["Entitlement gate", "PaymentRequest flow"],
  },
  {
    id: "profile-settings",
    title: "Profile & Settings",
    category: "Profile",
    image: "/screenshots/profile/settings.png",
    description: "Account centre with profile, professional details, preferences, security, and devices.",
    technicalNotes: ["SenderConfig", "Account lifecycle"],
  },
  {
    id: "admin-dashboard",
    title: "Admin Dashboard",
    category: "Admin",
    image: "/screenshots/admin/dashboard.png",
    description: "Admin overview with user statistics, recent registrations, subscription status, and system health.",
    technicalNotes: ["Cross-domain analytics", "AdminStatCard", "TrendChart"],
  },
  {
    id: "admin-users",
    title: "User Management",
    category: "Admin",
    image: "/screenshots/admin/users.png",
    description: "Full user administration with role/status control, approval queue, and activity timelines.",
    technicalNotes: ["DataTable", "Bulk operations", "Status machine"],
  },
  {
    id: "admin-approvals",
    title: "Approval Queue",
    category: "Admin",
    image: "/screenshots/admin/approvals.png",
    description: "Registration approval and payment verification workflows.",
    technicalNotes: ["requireAdmin guard", "AuditLog integration"],
  },
  {
    id: "admin-deliveries",
    title: "Email Deliveries",
    category: "Admin",
    image: "/screenshots/admin/deliveries.png",
    description: "Platform email monitoring with delivery status, bounce tracking, and dead-letter queue.",
    technicalNotes: ["NotificationDelivery", "Resend webhooks", "Svix"],
  },
  {
    id: "login-page",
    title: "Login",
    category: "Authentication",
    image: "/screenshots/auth/login.png",
    description: "Authentication page with username/password login and optional Google Sign-In.",
    technicalNotes: ["Cookie sessions", "bcryptjs", "CSRF protection"],
  },
  {
    id: "notifications-centre",
    title: "Notification Centre",
    category: "Notifications",
    image: "/screenshots/notifications/centre.png",
    description: "In-app notification centre with category filtering, read/unread state, and preferences.",
    technicalNotes: ["UserNotification", "Collapse grouping", "Dedup keys"],
  },
  {
    id: "support-ticket",
    title: "Support Ticket",
    category: "Support",
    image: "/screenshots/support/ticket.png",
    description: "Threaded support ticket with user and staff messages, internal notes, and attachments.",
    technicalNotes: ["SupportTicket", "TicketMessage", "File attachments"],
  },
  {
    id: "analytics-overview",
    title: "Analytics Dashboard",
    category: "Analytics",
    image: "/screenshots/analytics/overview.png",
    description: "Application and outreach analytics with charts, trends, and conversion metrics.",
    technicalNotes: ["Recharts", "Cross-domain read model"],
  },
  {
    id: "locations-view",
    title: "Location View",
    category: "Locations",
    image: "/screenshots/locations/view.png",
    description: "Per-location outreach view with companies, sending, and application tracking.",
    technicalNotes: ["CompanyList bucketing", "Location-scoped queries"],
  },
  {
    id: "search-palette",
    title: "Global Search",
    category: "Search",
    image: "/screenshots/search/palette.png",
    description: "Command palette (⌘K) with search across companies, applications, templates, and tickets.",
    technicalNotes: ["GIN trigram indexes", "User-scoped results"],
  },
];
