import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/layout/breadcrumbs";
import { PrevNextNav } from "@/components/layout/prev-next-nav";
import { Callout } from "@/components/ui/callout";

export const metadata: Metadata = { title: "Companies" };

export default function CompaniesFeaturePage() {
  return (
    <div className="w-full">
      <Breadcrumbs />
      <div className="mb-12">
        <h1 className="mb-4 text-4xl font-semibold tracking-tight text-[var(--color-fg)]">Companies</h1>
        <p className="text-xl text-[var(--color-fg-muted)] leading-relaxed">
          User-owned company lists, CSV ingestion, deduplication, and community contributions.
        </p>
      </div>

      <div className="prose max-w-none text-[15px] leading-relaxed text-[var(--color-fg-muted)]">
        <p>
          The <code>companies</code> feature slice owns the private, user-scoped company lists. It manages the <code>CompanyList</code> (a bucket for a specific location) and the <code>Company</code> models.
        </p>

        <h2 className="mt-12 mb-6 text-2xl font-medium tracking-tight text-[var(--color-fg)] border-b border-[var(--color-border-strong)] pb-4">
          The Data Model
        </h2>
        <p>
          The <code>Company</code> model is uniquely designed to prioritize UI simplicity. Instead of using nullable fields, almost all of its 20+ string columns (like <code>website</code>, <code>hrName</code>, and <code>techStack</code>) default to the literal string <code>"Not publicly listed"</code>. This prevents the frontend from needing constant null-coalescing fallbacks.
        </p>
        
        <h3 className="mt-8 mb-4 text-xl font-medium tracking-tight text-[var(--color-fg)]">Provenance & Sharing</h3>
        <ul className="list-disc pl-6 space-y-2 my-4">
          <li><strong><code>source</code></strong>: Tracks how the row entered the list (<code>manual</code>, <code>csv</code>, or <code>shared</code> from the global pool). This drives origin badges in the UI.</li>
          <li><strong><code>sharedWithCommunity</code></strong>: A boolean flag indicating the user contributed this specific row to the Global Company Pool. It only flips to <code>true</code> after a successful moderation and deduplication pass. It acts strictly as a visual badge—the private row remains fully editable and owned by the user, while a separate disconnected copy is placed in the public pool.</li>
        </ul>

        <h2 className="mt-12 mb-6 text-2xl font-medium tracking-tight text-[var(--color-fg)] border-b border-[var(--color-border-strong)] pb-4">
          Deduplication Invariants
        </h2>
        <p>
          Data ingestion—especially via CSV—is messy. To combat this, the slice relies heavily on normalized identity keys generated by <code>companyKeys()</code>.
        </p>
        <Callout type="warning" title="Strict Normalization Requirement">
          Dedupe keys and string normalization must be identical on both the write path (when inserting) and the read path (when querying), or matching silently fails. 
        </Callout>
        <p>
          These normalized keys power three critical systems without requiring a full table scan:
        </p>
        <ul className="list-disc pl-6 space-y-2 my-4">
          <li>The <strong>"Already in your list"</strong> warning badges in the shared community pool.</li>
          <li>The <strong>CSV Upload Dedupe Probe</strong> which actively prevents duplicates during bulk import.</li>
          <li>The <strong>Admin Duplicate Finder</strong> tools.</li>
        </ul>

        <h2 className="mt-12 mb-6 text-2xl font-medium tracking-tight text-[var(--color-fg)] border-b border-[var(--color-border-strong)] pb-4">
          Legacy Data
        </h2>
        <p>
          The schema retains an <code>industry</code> column. While the current version of the CSV import template no longer includes an Industry column, the field is retained strictly because it holds real data on existing rows and is still readable by the admin company editor.
        </p>
      </div>

      <PrevNextNav />
    </div>
  );
}
